version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: xpost-php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./app/public/.htaccess:/var/www/app/public/.htaccess
    env_file:
      - app/config/.env
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: docker/scheduler.Dockerfile
    container_name: xpost-scheduler
    volumes:
      - ./app:/var/www/app
    env_file:
      - app/config/.env
    depends_on:
      - php
    restart: unless-stopped

volumes:
  app:


